Capture g2sh as-evolved

diff --git a/gnash b/gnash
--- a/gnash
+++ b/gnash
@@ -1,22 +1,46 @@
 #!/bin/bash
 
+HOSTS=~/.ssh/known_hosts
+
+SSH_OPTS=(
+    '-o StrictHostKeyChecking=no'
+)
+
 die() {
-    >&2 echo "${0##*/}: $*"
+    warn $*
     exit 1
+}
+
+warn() {
+    >&2 echo "${0##*/}: $*"
 }
 
 info() { echo "==> $*"; }
 
 # TODO getopts
-[ -z "$1" ] && die "usage: $0 <host>"
+[ -z "$1" ] && die "usage: $0 <host> [wait|nocheck]"
 
-info "checking port 22"
-nc -zw2 "$1" 22 || die "'$1' not reachable on port 22"
+if [[ "$2" =~ ^w(ait)? ]]; then
+    info "waiting for icmp reply"
+    while ! ping -c2 -l2 -W1 "$1" |grep -q '64 bytes'; do sleep 1; done
 
-# TODO clean known_hosts?
-info "checking auth"
-env SSH_ASKPASS=~/bin/tellpass.sh setsid -w ssh-copy-id "$1" 2>/dev/null
-[ "$?" != 0 ] && die "couldn't install pubkey on '$1'"
+    info "waiting for port 22";
+    while ! nc -zw1 "$1" 22; do sleep 1; done
+else
+    if [[ ! "$2" =~ ^n(ocheck)? ]]; then
+        info "checking port 22"
+        nc -zw2 "$1" 22 || die "'$1' not reachable on port 22"
+    fi
+fi
+
+info "cleansing known_hosts file"
+perl -0pi -e "s/^\Q${1}\E(\.expertcity\.com)?,.*?\n//mg" "${HOSTS}"
+
+info "checking pubkey"
+env SSH_ASKPASS=~/bin/tellpass.sh \
+    setsid -w ssh-copy-id "${SSH_OPTS[@]}" "$1"
+
+[ "$?" != 0 ] && warn "couldn't install pubkey on '$1'"
 
 info "xfering"
 g2sh.pl "$1"
